# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SampleApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'OpenWrapSDK'
  pod 'OpenWrapBidder/FAN'
  pod 'FBAudienceNetwork', '5.8.0'

end
