# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SampleApp' do
    pod 'OpenWrapSDK'
    pod 'OpenWrapEventHandler/MoPub'
    pod 'mopub-ios-sdk', '5.10.0'
end
