# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!
target 'SampleApp' do
    pod 'OpenWrapSDK'
    pod 'OpenWrapHandlerMoPub'
    pod 'mopub-ios-sdk', '5.16.2'
end
