platform :ios, '10.0'
use_frameworks!

def required_pods
    pod 'Google-Mobile-Ads-SDK', '8.3.0'
    pod 'OpenWrapSDK'
    pod 'OpenWrapEventHandler/DFP'
end


target 'SampleApp' do
    required_pods
end

