platform :ios, '12.0'
use_frameworks!

def required_pods
    pod 'Google-Mobile-Ads-SDK', '12.0.0'
    pod 'OpenWrapSDK', '>=5.0.0'
    pod 'OpenWrapHandlerDFP', '>=6.0.0'
end


target 'SampleApp' do
    required_pods
end

