# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
use_frameworks!

target 'SampleApp' do
    pod 'Google-Mobile-Ads-SDK', '11.2.0'
    pod 'OpenWrapSDK', '>=3.5.0'
    pod 'OpenWrapHandlerDFP', '>=5.0.0'
end
