# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!

target 'SampleApp' do
    pod 'Google-Mobile-Ads-SDK', '8.3.0'
    pod 'OpenWrapSDK'
    pod 'OpenWrapEventHandler/DFP'
end
