# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
use_frameworks!

target 'SampleApp' do
    pod 'Google-Mobile-Ads-SDK', '12.0.0'
    pod 'OpenWrapSDK', '>=4.0.0'
    pod 'OpenWrapHandlerDFP', '>=5.2.0'
end
