platform :ios, '10.0'
use_frameworks!
def required_pods
    pod 'OpenWrapSDK'
    pod 'mopub-ios-sdk', '5.16.2'
    pod 'OpenWrapHandlerMoPub'
end


target 'SampleApp' do
    required_pods
end

target 'SampleAppTests' do
    required_pods
end

