platform :ios, '10.0'

def required_pods
    pod 'OpenWrapSDK'
    pod 'mopub-ios-sdk', '5.13.1'
    pod 'OpenWrapEventHandler/MoPub'
end


target 'SampleApp' do
    required_pods
end

target 'SampleAppTests' do
    required_pods
end

