# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'SampleApp' do
 
    pod 'Google-Mobile-Ads-SDK', '8.5.0'
    pod 'OpenWrapSDK', '2.0.0'
    pod 'OpenWrapEventHandler/DFP', '2.2.0'
    pod 'AmazonPublisherServicesSDK', '4.0.0'

end
