# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'SampleApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  # Pods for SampleApp
  pod 'OpenWrapSDK'
  pod 'OpenWrapBidder/FAN'
  pod 'FBAudienceNetwork', '6.2.0'
end
