# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!
target 'SampleApp' do
 
    pod 'mopub-ios-sdk', '5.16.2'
    pod 'OpenWrapSDK', '2.3.1'
    pod 'OpenWrapHandlerMoPub', '2.5.0'
    pod 'AmazonPublisherServicesSDK', '4.0.0'

end
