# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'SampleApp' do
  # Pods for SampleApp
     pod 'Google-Mobile-Ads-SDK', '10.3.0'
     pod 'OpenWrapSDK'
     pod 'OpenWrapHandlerDFP'
     pod 'AmazonPublisherServicesSDK', '4.0.0'
end
